/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "error": { "creationFunction": "CreateText", "text": "Uh oh! We had trouble talking to Backpack :(" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "status": { "creationFunction": "CreateText", "text": "Your status" },
    "text1": { "creationFunction": "CreateText", "text": "Add an entry" },
    "text2": { "creationFunction": "CreateText", "text": "Backpack URL:" },
    "text3": { "creationFunction": "CreateText", "text": "API Key:" },
    "text4": { "creationFunction": "CreateText", "text": "Who are you?" },
    "text5": { "creationFunction": "CreateText", "text": ".backpackit.com" }
};
